### ISSUE TITLE
Getting ''Uncaught SyntaxError: Unexpected end of input" while parsing some object arrays

### ISSUE THREAD

**Issue by gangeshwari-rajavelu** [oprogramador/read-json-lines-sync#39]
Noticed this error while passing  the jsonlines that comes as a result of parsing `yarn audit` output. This can be fixed by adding simple filters to ensure the line parsed is a json object.

**Comment by oprogramador** [comment]
@gangeshwari-rajavelu 

Thanks for reporting. I think it's a feature request.

So what do you expect for lines with invalid JSON?
- null?
- undefined?
- an empty object?
- omission of the result in the returned array?

**Comment by gangeshwari-rajavelu** [comment]
in the case i hit, the object was to be ommitted. was able to resolve it with a simple check of checking if the line starts with `{` and ends with `}`. Just opened a Pull request.
The file i was parsing was huge (`yarn audit` returned ~7500 vulnerabilities), it worked fine for  all other cases where the count was less than 500

**Comment by oprogramador** [comment]
@gangeshwari-rajavelu 

The fix is published in the `2.2.0` version.
